# Generated by Django 5.0.2 on 2024-03-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineshopuser',
            name='username',
            field=models.CharField(default='413bdef2-b736-462d-8ab3-ac2c56eb2408', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
