# Generated by Django 5.0.2 on 2024-03-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='car_body_type',
            field=models.CharField(default='audi', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='car_engine_modification',
            field=models.CharField(default='a5', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='car_engine_type',
            field=models.CharField(default='car', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='car_model',
            field=models.CharField(default='2.7', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='car_brand',
            field=models.CharField(max_length=50),
        ),
    ]
